electrogas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _
from induction import views
from controlcenter.views import controlcenter
import admin_reports

# Change admin site headre and title
admin.site.site_header = _("Administration")
admin.site.site_title = _("Administration")

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),
    path('overseer/', admin.site.urls),
    path('overseer/', controlcenter.urls),
    path('overseer/', admin_reports.site.urls),
    path('', include('induction.urls')),

    # Password reset urls
    path('reset-password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete')
]

handler404 = views.handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

induction/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'induction'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('terms/', views.terms, name='terms'),
    path('logout/', views.logout, name='logout'),
    path('course/', views.course, name='course'),
    path('course/<course_id>', views.course_detail, name='course_detail'),
    path('gotoquestion/', views.go_to_question, name='go_to_question'),
    path('question/', views.question, name='question'),
    path('certificate/<history_id>', views.certificate, name='certificate'),
    path('result/<history_id>', views.result, name='result'),
    path('history/', views.course_history, name='history'),
    path('profile/update/', views.update_profile, name='profile-update'),
    path('update-password/', views.update_password, name='password_update'),
    path('contractors/', views.contractor_list_by_company_and_id, name='contractor_list_by_company_and_id'),
    path('areas/', views.area_list, name='area_list'),
    path('employee/<area_id>', views.employee_list_by_area, name='employee_list_by_area'),
    path('user/<username>/', views.is_user_exist, name='is_user_exist'),
    path('contractor/<company_name>/<id_card>', views.is_contractor_exist, name='is_contractor_exist'),
    path('checkid/<id_card>', views.is_id_card_exist, name='is_employee_visitor_exist'),
    path('questionhistory/<history_id>', views.get_history_questions_list, name='questionhistory'),
    path('updatehistory/<history_id>/<video_id>', views.update_completed_video, name='update-history'),

    # Password reset urls
    path('reset-password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('email/', views.send_certificate_mail, name='certificate_mail'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.USER_IMAGE_URL, document_root=settings.USER_IMAGE_DIR)

induction/models/area.py
from django.db import models           

# Create your models here.		
class Area(models.Model):
	area_name = models.CharField('Area Name', max_length=255)

	def __str__(self):
		return str(self.area_name)

	class Meta:
		app_label = 'induction'
		ordering = ['-id']

induction/models/contractor.py
from django.db import models
from django.contrib.auth.models import User
import os
from uuid import uuid4
from django.utils.deconstruct import deconstructible
from induction.models.course import Course

# Create your models here.
@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)

class Contractor(User):
	contractor_course = models.ManyToManyField(Course, blank=True)
	contractor_company_name = models.CharField('Contractor', max_length=150, blank=True, null=True)
	contractor_phone_number = models.CharField('Phone Number', max_length=15, blank=True, null=True)
	contractor_photo = models.ImageField('Photo', upload_to=PathAndRename(''), blank=True)
	contractor_id_card_number = models.CharField('ID Card No', max_length=20, unique=True, blank=True, null=True)
	contractor_is_main = models.BooleanField('Is Main Contractor?',default=False)
	contractor_created_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
	contractor_updated_date = models.DateTimeField(auto_now=True, blank=True, null=True)

	def __str__(self):
		return str((self.contractor_company_name) + (('-' +self.contractor_id_card_number) if self.contractor_id_card_number else ''))

	class Meta:
		app_label = 'induction'
		unique_together = ('contractor_company_name', 'contractor_id_card_number',)

induction/models/course.py
from django.db import models
from induction.models.custom_fields import PositiveTinyIntegerField, PositiveSmallIntegerField, PositiveFloatField
from induction.models.video import Video

# Create your models here.
class Course(models.Model):
	INACTIVE='Inactive'
	ACTIVE='Active'
	STATUS_CHOICES = (
    	(INACTIVE, 'Inactive'),
    	(ACTIVE, 'Active')
    )

	course_title = models.CharField('Course Title', max_length=255)
	course_description = models.CharField(max_length=2000)
	course_validity = PositiveSmallIntegerField('Validity [days]', help_text="Enter 0 for no course validity.")
	course_passing_percentage = PositiveFloatField('Passing Percentage [%]')

	course_video = models.ManyToManyField(Video)

	course_auto_assigned = models.BooleanField(default=False)
	course_status = models.CharField('Status', max_length=8, choices=STATUS_CHOICES, default=ACTIVE)
	course_created_date = models.DateTimeField(auto_now_add=True)
	course_updated_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return str(self.course_title)

	class Meta:
		app_label = 'induction'

induction/models/electrogasuser.py
from django.db import models
from django.contrib.auth.models import User
import os
from datetime import datetime
from uuid import uuid4
from django.utils.deconstruct import deconstructible
from induction.models.course import Course
from django.contrib.auth.models import PermissionsMixin

# Create your models here.
@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)

class AdminUser(User, PermissionsMixin):
    user_phone_number = models.CharField('Phone Number', max_length=15, blank=True, null=True)
    user_course = models.ManyToManyField(Course, blank=True)
    user_photo = models.ImageField('Photo', upload_to=PathAndRename(''), blank=True)
    user_id_card_number = models.CharField('ID Card No', max_length=20, blank=True, null=True)
    def __str__(self):
        return str(self.username)
    class Meta:
        app_label = 'induction'

induction/models/option.py
from django.db import models
from induction.models.question import Question

# Create your models here.
class Option(models.Model):
	option_question = models.ForeignKey(Question, on_delete=models.CASCADE)
	option_title = models.CharField(max_length=1000)
	option_is_answer = models.BooleanField('Is Answer', default=False)

	def __str__(self):
		return str(self.option_title)

	class Meta:
		app_label = 'induction'

induction/forms/contractorform.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from induction.models.contractor import Contractor
from induction.models.course import Course
from django.utils.translation import gettext as _
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class ContractorChangeForm(UserChangeForm):
	username = forms.CharField(required=True, min_length=5)
	contractor_course = forms.ModelMultipleChoiceField(
          queryset=Course.objects.all().filter(course_status='Active'),
          required=False,
          widget=FilteredSelectMultiple(
              verbose_name=_('Courses'),
              is_stacked=False
          ),
          label=_('Select Courses')
    )

	def __init__(self, *args, **kwargs):
		super(ContractorChangeForm, self).__init__(*args, **kwargs)
		self.fields['email'].required = True
		if self.instance and self.instance.pk:
			self.fields['contractor_course'].initial = self.instance.contractor_course.all().filter(course_status='Active')

	class Meta:
		model = Contractor
		fields = '__all__'

class ContractorCreationForm(UserCreationForm):
	username = forms.CharField(required=True, min_length=5)
	def __init__(self, *args, **kwargs):
		super(ContractorCreationForm, self).__init__(*args, **kwargs)
		self.fields['email'].required = True

	def clean_email(self):
		email = self.cleaned_data['email']
		if User.objects.filter(email=email).exists():
			raise ValidationError("Email already exists")
		return email

	class Meta:
		model = Contractor
		fields = '__all__'	
			

induction/forms/courseform.py
from django import forms
from induction.models.video import Video
from induction.models.course import Course
from django.utils.translation import gettext as _
from django.contrib.admin.widgets import FilteredSelectMultiple
from tinymce.widgets import TinyMCE

class CourseForm(forms.ModelForm):
    course_video = forms.ModelMultipleChoiceField(
          queryset=Video.objects.all().filter(video_status='Active'),
          required=True,
          widget=FilteredSelectMultiple(
              verbose_name=_('Videos'),
              is_stacked=False
          ),
          label=_('Select Videos')
    )

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)

        if self.instance and self.instance.pk:
            self.fields['course_video'].initial = self.instance.course_video.all().filter(video_status='Active')

    course_description = forms.CharField(widget=TinyMCE(attrs={'cols': 65, 'rows': 15}), label='Description')
    class Meta:
        model = Course
        fields = '__all__'
			

induction/forms/electrogasuserform.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from induction.models.electrogasuser import AdminUser
from tinymce.widgets import TinyMCE
from induction.models.course import Course
from django.utils.translation import gettext as _
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.models import Permission, Group
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class ElectrogasUserChangeForm(UserChangeForm):
	username = forms.CharField(required=True, min_length=5)
	# get_restricted_perm_list = ['logentry','group','permission','user','contenttype','session']
	# content_id_list = []
	# for c in get_restricted_perm_list:
	# 	content = ContentType.objects.get(model=c)
	# 	content_id_list.append(content.id)
	# print(content_id_list)
	# groups = forms.ModelMultipleChoiceField(
 #          queryset=Group.objects.filter().exclude(name__in = ["Contractor","Employee","Visitor"]),
 #          required=False,
 #          widget=FilteredSelectMultiple(
 #              verbose_name=_('Group'),
 #              is_stacked=False
 #          ),
 #          label=_('Select Group')
 #    )
 	
	# [1,2,3,5,6] [12,13,14,16,17] [13,14,15,17,18]
	user_permissions = forms.ModelMultipleChoiceField(
          queryset=Permission.objects.filter().exclude(content_type_id__in = [13,14,15,17,18]),
          required=False,
          widget=FilteredSelectMultiple(
              verbose_name=_('Persmission'),
              is_stacked=False
          ),
          label=_('Select Permission')
    )
	user_course = forms.ModelMultipleChoiceField(
          queryset=Course.objects.all().filter(course_status='Active'),
          required=False,
          widget=FilteredSelectMultiple(
              verbose_name=_('Courses'),
              is_stacked=False
          ),
          label=_('Select Courses')
    )

	def __init__(self, *args, **kwargs):
		super(ElectrogasUserChangeForm, self).__init__(*args, **kwargs)
		self.fields['email'].required = True
		if self.instance and self.instance.pk:
			self.fields['user_course'].initial = self.instance.user_course.all().filter(course_status='Active')
			
	class Meta:
		model = AdminUser
		fields = '__all__'

class ElectrogasUserCreationForm(UserCreationForm):
	username = forms.CharField(required=True, min_length=5)
	def __init__(self, *args, **kwargs):
		super(ElectrogasUserCreationForm, self).__init__(*args, **kwargs)
		self.fields['email'].required = True
	def clean_email(self):
 		email = self.cleaned_data['email']
 		if User.objects.filter(email=email).exists():
 			raise ValidationError("Email already exists")
 		return email
	class Meta:
		model = AdminUser
		fields = '__all__'
			

induction/forms/employeeform.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from induction.models.employee import Employee
from induction.models.contractor import Contractor
from induction.models.course import Course
from django.utils.translation import gettext as _
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class EmployeeChangeForm(UserChangeForm):
	# employee_course = forms.ModelMultipleChoiceField(
 #          queryset=Course.objects.all(),
 #          required=False,
 #          widget=FilteredSelectMultiple(
 #              verbose_name=_('Courses'),
 #              is_stacked=False
 #          ),
 #          label=_('Select Courses')
 #    )
 	username = forms.CharField(required=True, min_length=5)
 	def __init__(self, *args, **kwargs):
 		super(EmployeeChangeForm, self).__init__(*args, **kwargs)
 		self.fields['email'].required = True
 		if self.current_user.groups.all().filter(name='Contractor').exists():
 			self.fields['employee_contractor'].widget = forms.HiddenInput()
 			self.fields['employee_contractor'].initial = self.current_user.id
 	class Meta:
 		model = Employee
 		fields = '__all__'

class EmployeeCreationForm(UserCreationForm):
	username = forms.CharField(required=True, min_length=5)
	def __init__(self, *args, **kwargs):
		# self.groups = 'Employee'
		super(EmployeeCreationForm, self).__init__(*args, **kwargs)
		self.fields['email'].required = True
		if self.current_user.groups.all().filter(name='Contractor').exists():
			self.fields['employee_contractor'].widget = forms.HiddenInput()
			self.fields['employee_contractor'].initial = self.current_user.id

	def clean_email(self):
 		email = self.cleaned_data['email']
 		if User.objects.filter(email=email).exists():
 			raise ValidationError("Email already exists")
 		return email
	class Meta:
		model = Employee
		fields = '__all__'
			

induction/forms/historyform.py
from django import forms

class HistoryForm(forms.Form):
	ALL='All'
	PASS='Pass'
	FAIL='Fail'
	PENDING='Pending'

	COMPLETED = 'Completed'
	ATTEMPTED = 'Attempted'
	NOT_ATTEMPTED = 'Not Attempted'

	RESULT_CHOICES = ((ALL,'All'),(PASS,'Pass'),(FAIL,'Fail'),(PENDING,'Pending'))
	STATUS_CHOICES = ((ALL,'All'),(COMPLETED,'Completed'),(ATTEMPTED,'Attempted'),(NOT_ATTEMPTED,'Not Attempted'))
	course_complete_date_from = forms.CharField(label="From Complete Date", required=False)
	course_complete_date_to = forms.CharField(label="To Complete Date", required=False)
	status = forms.ChoiceField(label="Status", choices=STATUS_CHOICES, required=False)
	result = forms.ChoiceField(label="Result", choices=RESULT_CHOICES, required=False)
	course = forms.CharField(label="Course", required=False)
	first_name = forms.CharField(label="First Name", required=False)
	last_name = forms.CharField(label="Last Name", required=False)
	contractor = forms.CharField(label="Contractor", required=False)

			

induction/forms/sitesettingsform.py
from django import forms
from induction.models.site_settings import SiteSetting
from tinymce.widgets import TinyMCE

class SiteSettingsForm(forms.ModelForm):
    welcome_note = forms.CharField(widget=TinyMCE(attrs={'cols': 65, 'rows': 15}), label='Welcome Note')
    course_list_note = forms.CharField(widget=TinyMCE(attrs={'cols': 65, 'rows': 15}), label='Note about Course list')
    
    class Meta:
        model = SiteSetting
        fields = '__all__'
			

induction/templates/induction/certificate.html
{% extends 'induction/base.html' %}
{% load static %}

{% block main %}

<main class="site-main">
    <nav class="breadcrumb-wrap" aria-label="breadcrumb">
    <div class="container">
      <div class=" row justify-content-center">
        <ol class="breadcrumb col col-12 col-sm-10 col-lg-9 col-xl-8">
          <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'induction:index' %}">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'induction:course' %}">My Courses</a></li>
          <li class="breadcrumb-item active" aria-current="page">Certificate</li>
        </ol>
       </div>
     </div>
    </nav>

    <section class="section">
      <div class="container">

        <div class="row justify-content-center">
           {% if messages %}
            <div class="col-md-12" align="center">
              <div class="alert alert-success">
                {% for message in messages %}
                 {{ message }}
                {% endfor %}
              </div>
            </div>
            {% endif %}

          <div class="col col-12 col-sm-10 col-lg-9 col-xl-8">
            
            <div id='certificate_body' style="color: #495057;">

                <div style="width:800px; height:600px; padding:20px; text-align:center; border: 10px solid #787878">
                <div style="width:750px; height:550px; padding:20px; text-align:center; border: 5px solid #787878">

                    <div><img src="{% static 'induction/electrogas-logo-240w.png' %}"></div>
                    <div style="font-size:50px; font-weight:bold; color: #495057;">Certificate of Completion</div>
                    
                    <div style="font-size:22px; margin-bottom: 5px;"><i>This is to certify that</i></div>
                   

                    <div style="font-size:30px; margin-bottom: 5px;"><b>
                      {% if user_session.first_name and user_session.last_name %}
                        {{ user_session.first_name }} {{ user_session.last_name }}
                      {% elif user_session.first_name %}
                        {{ user_session.first_name }}
                      {% else %}
                        {{ user_session.username }}
                      {% endif %}
                    </b></div>


                    <div style="font-size:22px; margin-bottom: 5px;"><i>has completed the course</i></div> 

                    <div style="font-size:30px; margin-bottom: 5px;">{{ history_data.course.course_title }}</div> 

                    <div style="font-size:22px; margin-bottom: 5px;"><i>with score of <b>{{history_data.user_course_obtained_percentage|floatformat:2}}%</i></b></div>
                    <div style="font-size:22; margin-bottom: 5px;"><i>Completed Date: {{ history_data.user_course_complete_date.date }}</i></div>

                    
                    <div style="font-size:22; margin-bottom: 5px;"><i>Expiry Date: {% if history_data.user_course_validity > 0 %}{{ history_data.user_course_expiry_date.date }}{% else %} -------- {% endif %}</i></div>

                    <div>
                      <img src="{% static 'induction/BumiArmada.JPG' %}" style="width: 70px;height:50px;"> 
                      <img src="{% static 'induction/es3.jpeg' %}" style="width: 70px;height:50px;">
                      <img src="{% static 'induction/Logo Reganosa.jpeg' %}" style="width: 70px;height:50px;">
                      <img src="{% static 'induction/SGS.jpg' %}" style="width: 70px;height:50px;">
                    </div>
                    
               
                    <table style="margin-top:10px;float:right">
                      <tr>
                        <td><div><b>Electrogas Organisation</b></div></td>
                      </tr>
                      <tr>
                        <td style="width:190px;float:right;border:0;border-bottom:1px solid #000;"></td>
                      </tr>
                      <tr>
                        <td style="text-align:center"><div><b>Signature</b></div></td>
                      </tr>
                    </table>
                </div>
              </div>
            </div>

          </div>
        </div>

        <div class="row justify-content-center">
          <div class="col col-12 col-sm-10 col-lg-9 col-xl-8">
            <div class="btn-wrap row justify-content-between">
               <span><a href="{% url 'induction:course' %}" class="btn btn-primary" style='float: left;'>Go to course</a></span>
               
              <span><form method="post" action="{% url 'induction:certificate_mail' %}">
                 {% csrf_token %}
                 <input type="hidden" name="history_id" value="{{ history_data.id }}">
                 <input type="hidden" name="course_name" value="{{ history_data.course.course_title }}">
                 <input type="hidden" name="percentage" value="{{history_data.user_course_obtained_percentage|floatformat:2}}">
                 <input type="hidden" name="completeddate" value="{{ history_data.user_course_complete_date.date }}">
                 <input type="hidden" name="expirydate" value="{{ history_data.user_course_expiry_date.date }}">
                 <input type="hidden" name="course_validity" value="{{ history_data.user_course_validity }}">
                 
                 <button class="btn btn-primary" align = "center" type="submit">Send Certificate by Email</button>
              </form></span>

              <span><a href="#" class="btn btn-primary" id="printCertificate">Print Certificate</a></span>
            </div>
          </div>
        </div>

      </div>
    </section>
  </main>

<script src="{% static 'induction/js/certificate.js' %}" ></script>
  {% endblock %}

induction/templates/induction/course_detail.html
{% extends 'induction/base.html' %}
{% load custom_filters %}
{% load static %}

{% block main %}

<main class="site-main">
    <nav class="breadcrumb-wrap" aria-label="breadcrumb">
    <div class="container">
      <div class=" row justify-content-center">
        <ol class="breadcrumb col col-12 col-sm-10 col-lg-9 col-xl-8">
          <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'induction:index' %}">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'induction:course' %}">My Courses</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{ course.course_title }}</li>
        </ol>
       </div>
     </div>
    </nav>

    <section class="section">
      <div class="container">

        <div class="row justify-content-center">
          <div class="col col-12 col-sm-10 col-lg-9 col-xl-8">
            <h4>{{ course.course_title }}</h4>
            {% if course %}<p>{{ course.course_description|safe }}</p>{% endif %}
          </div>
        </div>
       

        <div class="row justify-content-center">
          <div class="col col-12 col-sm-10 col-lg-9 col-xl-8">

            {% for video in video_list %}
            <div class="row mt-5 justify-content-center">
              <div class="col col-12 col-sm-10">
                  <div class="embed-responsive embed-responsive-16by9" id=video-placeholder>
                    <input type="hidden" id="videoID" value="{{video.id}}">
                    <input type="hidden" id="youTubeVideoId" value="{{video.video_url|get_youtube_video_id}}">
                  </div>
                <div class="mt-2" align="center"><small ><strong>{{video.video_title}}</strong></small></div>
                <!-- <div class="mt-2" align="center"><small ><strong id=current-time></strong></small></div> -->
                <!-- <div class="mt-2" align="center"><small ><strong id =duration></strong></small></div> -->
                <hr>
              </div>
            </div>
            {% endfor %}
            
            <div class="row mt-5 justify-content-center">
              <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">

                  <li class="page-item{% if not video_list.has_previous %} disabled{% endif %}">
                    <a class="page-link" href="{% if video_list.has_previous %}?page={{ video_list.previous_page_number }}{% endif %}" {% if not video_list.has_previous %}tabindex="-1"{% endif %}>Previous</a>
                  </li>
                 
                  {% for pg in video_list.paginator.page_range %}
                    <li class='page-item{% if pg >= current_page %}{% if page|stringformat:"s" != pg|stringformat:"s" %} {% if page %} disabled {% else %} {% if forloop.counter != 1 %} disabled{% endif %}{% endif %}{% endif %}{% endif %}'><a class="page-link" href="?page={{ pg }}"  tabindex="{% if page|stringformat:'s' != pg|stringformat:'s' %} -1{% endif %}" style="{% if page|stringformat:'s' == pg|stringformat:'s' %}background-color: #00aaac; color: #ffffff;{% endif %}">{{ pg }}</a></li>
                  {% endfor %}

                  
                  <li id="next-button" class="page-item {% if not video_list.has_next %} disabled{% endif %}">
                    <a class="page-link" href="{% if video_list.has_next %}?page={{ video_list.next_page_number }}{% endif %}" {% if not video_list.has_next %}tabindex="-1"{% endif %}>Next</a>
                  </li> 
                 

                </ul>
              </nav>
            </div>

            {% if not video_list.has_next %}
            <div class="btn-wrap" id="btnQuestionnaire" style="display: none; margin-top: 0px;">
              <form method="post" action="{% url 'induction:go_to_question' %}">
                 {% csrf_token %}
                 <button class="btn btn-primary" type="submit">Go To Questionnaire</button>
              </form>
            </div>
            {% endif %}

          </div>
        </div>
        
      </div>
    </section>
  </main>
  <script type="text/javascript">
    var is_completed = "{{is_completed}}";
    var page = "{{page}}";
    var last_page = "{{last_page}}";
    var history_id = "{{history_id}}"
  </script>
  <script src="{% static 'induction/js/youtubecontrol.js' %}" ></script>
<script src="{% static 'induction/js/iframe_api.js' %}" ></script>
<!-- <script src="https://www.youtube.com/iframe_api"></script> -->
  {% endblock %}

induction/templates/induction/header.html
	
{% load static %}
<div class="d-block text-center mt-5 mb-5 .container-fluid">
	<h1><a href="{% url 'induction:index' %}"><img src="{% static 'induction/electrogas-logo-240w.png' %}"></a></h1>
</div>

induction/templates/induction/main_header.html
	
{% load static %}
<header class="site-header fixed-top">
	<div class="container">
		<nav class="navbar navbar-expand">
			<a class="navbar-brand" href="{% url 'induction:index' %}"><img src="{% static 'induction/electrogas-logo-240w.png' %}"></a>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav ml-auto">
				<li class="nav-item dropdown">
				  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					  <div class="user-icon">
						  <img src="{% static 'induction/man.png' %}" alt="User Icon">
					  </div>
					Hi, {% if user_session.first_name%}
                          {{ user_session.first_name }}
                        {% else %}
                          {{ user_session.username }}
                        {% endif %}
				  </a>
				  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="{% url 'induction:course' %}">My Courses</a>
					<a class="dropdown-item" href="{% url 'induction:history' %}">Courses History</a>
					<a class="dropdown-item" href="{% url 'induction:profile-update' %}">My Profile</a>
					<a class="dropdown-item" href="{% url 'induction:password_update' %}">Change Password</a>
					<!-- <a class="dropdown-item" href="#"> Logout</a> -->
					<form method="post" action="{% url 'induction:logout' %}">
						{% csrf_token %}
						<button class="dropdown-item" type="submit">Logout</button>
					</form>
				  </div>
				</li>
			  </ul>
			</div>
		  </nav>
	</div>
</header>